# Generated by Django 3.2.5 on 2022-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221002_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='taskId',
        ),
        migrations.AddField(
            model_name='subtask',
            name='taskId',
            field=models.ManyToManyField(to='account.Task'),
        ),
    ]
