# Generated by Django 3.2.5 on 2022-10-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20221002_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='taskId',
        ),
        migrations.AddField(
            model_name='subtask',
            name='taskId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.task'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.subtask'),
        ),
    ]
