# Generated by Django 3.2.5 on 2022-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20221002_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(null=True, related_name='subtasks', to='account.Subtask'),
        ),
    ]
