# Generated by Django 3.2.5 on 2022-10-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20221002_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='taskId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='account.task'),
        ),
    ]
