# Generated by Django 3.2.5 on 2022-10-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_subtask_taskid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tasks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.task')),
            ],
        ),
    ]
