# Generated by Django 3.2.5 on 2022-10-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.column'),
        ),
    ]
