# Generated by Django 3.2.5 on 2022-10-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_column_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='account.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='account.column'),
        ),
    ]
