# Generated by Django 3.2.5 on 2022-10-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_task_column_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='tasks',
        ),
    ]
